/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.web.controller;

import com.smart.cons.CommonConstant;
import com.smart.dao.Page;
import com.smart.domain.Board;
import com.smart.domain.Post;
import com.smart.domain.Topic;
import com.smart.domain.User;
import com.smart.service.ForumService;
import com.smart.web.BoardManageController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.servlet.ModelAndView;
import org.testng.annotations.Test;
import org.unitils.spring.annotation.SpringBeanByType;

import static org.testng.Assert.*;


public class BoardManageControllerTest  extends BaseWebTest {
	@Autowired
	private ForumService forumService;
	@SpringBeanByType
	private BoardManageController controller;

	@Test
	public void listBoardTopics() throws Exception {
		request.setRequestURI("/board/listBoardTopics-1");
		request.addParameter("boardId", "1"); // ⑥ 设置请求URL及参数
		request.setMethod("GET");
		ModelAndView mav =  controller.listBoardTopics(1,1);
		Board board = (Board) mav.getModelMap().get("board");
		assertNotNull(mav);
		assertEquals(mav.getViewName(), "/listBoardTopics");
		assertNotNull(board);
		assertEquals(board.getBoardName(), "SpringMVC");// ⑧ 验证返回结果
	}


	@Test
	public void addTopicPage() throws Exception {
		request.setRequestURI("/board/addTopicPage-1");
		request.setMethod("GET");
		ModelAndView mav =  controller.addTopicPage(1);
		assertNotNull(mav);
		assertEquals(mav.getViewName(), "/addTopic");
	}

	@Test
	public void addTopic()throws Exception  {
		request.setRequestURI("/board/addTopic");
		request.setMethod("POST");

		User user = new User();
		user.setUserId(1);
		user.setUserName("tom");
		user.setPassword("1234");
		request.getSession().setAttribute(CommonConstant.USER_CONTEXT, user);
		session.setAttribute(CommonConstant.USER_CONTEXT, user);

		Topic topic = new Topic();
		topic.setTopicTitle("SpringMVC集成");
		topic.setBoardId(1);
		topic.getMainPost().setPostTitle("SpringMVC集成");
		topic.getMainPost().setPostText("SpringMVC集成！！");

		String mav = controller.addTopic(request, topic);
		assertNotNull(mav);
	}

	@Test
	public void listTopicPosts()throws Exception  {
		request.setRequestURI("/board/listTopicPosts-1");
		request.addParameter("topicId", "1");
		request.setMethod("GET");
		ModelAndView mav = controller.listTopicPosts(1,1);

		Topic topic = (Topic) mav.getModelMap().get("topic");
		Page pagedPost = (Page) mav.getModelMap().get("pagedPost");

		assertNotNull(topic);
		assertNotNull(pagedPost);
		assertEquals(pagedPost.getPageSize()>0, true);
		assertNotNull(mav);
		assertEquals(mav.getViewName(), "/listTopicPosts");
	}


	@Test
	public void addPost()throws Exception  {
		request.setRequestURI("/board/addPost");
		request.addParameter("topicId", "1");
		Post post = new Post();
		post.setBoardId(1);
		post.setPostTitle("SpringMVC集成");
		post.setPostText("SpringMVC集成！！");

		request.setMethod("POST");

		User user = new User();
		user.setUserId(1);
		user.setUserName("tom");
		user.setPassword("1234");
		request.getSession().setAttribute(CommonConstant.USER_CONTEXT, user);
		session.setAttribute(CommonConstant.USER_CONTEXT, user);

		controller.addPost(request,post );
	}

}
